name: Collect Dynamic Data

on:
  schedule:
    # # At 18:30 UTC on Sunday (12.00 mid night in Sri Lanka)
    - cron: "30 18 * * 0"

    # # At 18:30 UTC on everyday (12.00 mid night in Sri Lanka)
    # - cron: "0 0 * * *"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          package-manager-cache: false

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the Python script
        run: |
          cd ./python_scripts/
          python dynamic_data.py
          python projects_latest.py
          python projects_popular.py

      - name: Format files
        run: |
          npm install --global prettier
          prettier --write "**/*.{js,json,md,yml,yaml,html,css,scss}" \
          --config .prettierrc \
          --ignore-path .prettierignore

      - name: Commit and push into the main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Dynamic data updated" || echo "No changes to commit"
          git push
